/*Testing ...
   ... 1 ...
     ... 2 ...
       ... 3 ...
*/
public class Testing123 {
  public static void main(String[] args) {
    System.out.println("\t... 1 ...\n\t\t... 2 ...\n\t\t\t... 3 ...");
  }
}
